### ISSUE TITLE
feature request: more than one request with one fixed interval

### ISSUE THREAD

**Issue by HorstBuchholz** [hacki11/ioBroker.bsblan#195]
For collecting a lot of data from the heating device / heatpump it would be fine to have **more than one request with one interval** time.
Some temperatures (e.g. heat gas on heat pump) are interesting with a short interval while other values can be read with a longer interval time. So the data traffic can be reduced when logging a lot of data values.

**Comment by hacki11** [comment]
Hey, thank you for your feedback.

What interval times do you have in mind? Is the traffic an issue for you? Is it a connection based on volume or is the logging of the values the issue? Can you go a bit into the issue you currently face if you collect everything at the same interval? I think we are talking about some kilo bytes, a reduction of that won't make a difference on a modern connection. Or is it impossible to read all the values because the bsblan device is too slow in responding?

It is also possible to push values from bsblan via mqtt to iobroker. Perhaps for those which change so frequently it could also be an option to use mqtt.

**Comment by hacki11** [comment]
Feel free to reopen if you can provide further input.
